[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
gas_reports = ["*"]

[lint]
exclude_lints = ["screaming-snake-case-immutable"]


[fmt]
number_underscore = "thousands"
